#!/bin/sh

echo "=== Manual SSH Test ==="
echo "Run these commands one by one to test SSH manually:"
echo ""
echo "1. Kill any existing SSH processes:"
echo "   pkill -x sshd"
echo "   fuser -k 2222/tcp"
echo ""
echo "2. Test the SSH config:"
echo "   /usr/sbin/sshd -t -f /etc/ssh/sshd_config"
echo ""
echo "3. Start SSH in foreground (for debugging):"
echo "   /usr/sbin/sshd -D -p 2222 -o PasswordAuthentication=yes -o PermitRootLogin=no"
echo ""
echo "4. Or start SSH in background:"
echo "   /usr/sbin/sshd -p 2222 -o PasswordAuthentication=yes -o PermitRootLogin=no"
echo ""
echo "5. Check if it's running:"
echo "   ps aux | grep sshd"
echo "   netstat -ltn | grep 2222"
echo ""
echo "6. Test connection from same machine:"
echo "   ssh samsara@localhost -p 2222"
echo ""
echo "========================"

echo ""
echo "Current status:"
echo "SSH processes:"
ps aux | grep sshd | grep -v grep || echo "No SSH processes"
echo ""
echo "Port 2222 status:"
netstat -ltn | grep 2222 || echo "Nothing on port 2222"
echo ""
echo "User samsara:"
id samsara 2>/dev/null || echo "User samsara not found"
